// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';
import {appkit} from '../models';

export function CompleteMaintenanceEvent(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number,arg7:string):Promise<db.CompletionResult>;

export function DeleteMaintenanceEvent(arg1:string):Promise<void>;

export function DeleteProperty(arg1:string):Promise<void>;

export function DeleteServiceProvider(arg1:string):Promise<void>;

export function DeleteSystem(arg1:string):Promise<void>;

export function GetEventHistory(arg1:string):Promise<Array<db.MaintenanceHistoryRec>>;

export function GetLastRoute():Promise<string>;

export function GetMaintenanceEvent(arg1:string):Promise<db.MaintenanceEvent>;

export function GetMaintenanceEvents(arg1:string):Promise<Array<db.MaintenanceEvent>>;

export function GetProperties():Promise<Array<db.Property>>;

export function GetProperty(arg1:string):Promise<db.Property>;

export function GetServiceProvider(arg1:string):Promise<db.ServiceProvider>;

export function GetServiceProviders(arg1:string):Promise<Array<db.ServiceProvider>>;

export function GetSidebarWidth():Promise<number>;

export function GetSystem(arg1:string):Promise<db.System>;

export function GetSystems(arg1:string):Promise<Array<db.System>>;

export function GetTab(arg1:string):Promise<string>;

export function GetTabRoute(arg1:string):Promise<string>;

export function GetTableState(arg1:string):Promise<appkit.TableState>;

export function LogDebug(arg1:string):Promise<void>;

export function LogError(arg1:string):Promise<void>;

export function LogInfo(arg1:string):Promise<void>;

export function LogWarning(arg1:string):Promise<void>;

export function SaveLastRoute(arg1:string):Promise<void>;

export function SaveMaintenanceEvent(arg1:db.MaintenanceEvent):Promise<db.MaintenanceEvent>;

export function SaveProperty(arg1:db.Property):Promise<db.Property>;

export function SaveServiceProvider(arg1:db.ServiceProvider):Promise<db.ServiceProvider>;

export function SaveSystem(arg1:db.System):Promise<db.System>;

export function SaveWindowGeometry(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function SetSidebarWidth(arg1:number):Promise<void>;

export function SetTab(arg1:string,arg2:string):Promise<void>;

export function SetTabRoute(arg1:string,arg2:string):Promise<void>;

export function SetTableState(arg1:string,arg2:appkit.TableState):Promise<void>;
