// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompleteMaintenanceEvent(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['app']['App']['CompleteMaintenanceEvent'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function DeleteMaintenanceEvent(arg1) {
  return window['go']['app']['App']['DeleteMaintenanceEvent'](arg1);
}

export function DeleteProperty(arg1) {
  return window['go']['app']['App']['DeleteProperty'](arg1);
}

export function DeleteServiceProvider(arg1) {
  return window['go']['app']['App']['DeleteServiceProvider'](arg1);
}

export function DeleteSystem(arg1) {
  return window['go']['app']['App']['DeleteSystem'](arg1);
}

export function GetEventHistory(arg1) {
  return window['go']['app']['App']['GetEventHistory'](arg1);
}

export function GetLastRoute() {
  return window['go']['app']['App']['GetLastRoute']();
}

export function GetMaintenanceEvent(arg1) {
  return window['go']['app']['App']['GetMaintenanceEvent'](arg1);
}

export function GetMaintenanceEvents(arg1) {
  return window['go']['app']['App']['GetMaintenanceEvents'](arg1);
}

export function GetProperties() {
  return window['go']['app']['App']['GetProperties']();
}

export function GetProperty(arg1) {
  return window['go']['app']['App']['GetProperty'](arg1);
}

export function GetServiceProvider(arg1) {
  return window['go']['app']['App']['GetServiceProvider'](arg1);
}

export function GetServiceProviders(arg1) {
  return window['go']['app']['App']['GetServiceProviders'](arg1);
}

export function GetSidebarWidth() {
  return window['go']['app']['App']['GetSidebarWidth']();
}

export function GetSystem(arg1) {
  return window['go']['app']['App']['GetSystem'](arg1);
}

export function GetSystems(arg1) {
  return window['go']['app']['App']['GetSystems'](arg1);
}

export function GetTab(arg1) {
  return window['go']['app']['App']['GetTab'](arg1);
}

export function GetTabRoute(arg1) {
  return window['go']['app']['App']['GetTabRoute'](arg1);
}

export function GetTableState(arg1) {
  return window['go']['app']['App']['GetTableState'](arg1);
}

export function LogDebug(arg1) {
  return window['go']['app']['App']['LogDebug'](arg1);
}

export function LogError(arg1) {
  return window['go']['app']['App']['LogError'](arg1);
}

export function LogInfo(arg1) {
  return window['go']['app']['App']['LogInfo'](arg1);
}

export function LogWarning(arg1) {
  return window['go']['app']['App']['LogWarning'](arg1);
}

export function SaveLastRoute(arg1) {
  return window['go']['app']['App']['SaveLastRoute'](arg1);
}

export function SaveMaintenanceEvent(arg1) {
  return window['go']['app']['App']['SaveMaintenanceEvent'](arg1);
}

export function SaveProperty(arg1) {
  return window['go']['app']['App']['SaveProperty'](arg1);
}

export function SaveServiceProvider(arg1) {
  return window['go']['app']['App']['SaveServiceProvider'](arg1);
}

export function SaveSystem(arg1) {
  return window['go']['app']['App']['SaveSystem'](arg1);
}

export function SaveWindowGeometry(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SaveWindowGeometry'](arg1, arg2, arg3, arg4);
}

export function SetSidebarWidth(arg1) {
  return window['go']['app']['App']['SetSidebarWidth'](arg1);
}

export function SetTab(arg1, arg2) {
  return window['go']['app']['App']['SetTab'](arg1, arg2);
}

export function SetTabRoute(arg1, arg2) {
  return window['go']['app']['App']['SetTabRoute'](arg1, arg2);
}

export function SetTableState(arg1, arg2) {
  return window['go']['app']['App']['SetTableState'](arg1, arg2);
}
